const templates = [
  {
    id: 723,
    owner: "Ethan B. Rodriguez",
    image: "/images/postImages/user--2.avif",
    template: "/images/Marketing/template--3.jpg",
    templateName: "Smart Home Automation Control Panel Template",
    rating: 8,
    reviews: 142,
    price: 85,
    coin: 15,
    tier: "paid",
    category: "portfolio",
    under: "templates",
  },
  {
    id: 156,
    owner: "Sophia L. Garcia",
    image: "/images/Marketing/user--8.avif",
    template: "/images/Marketing/portfolio--2.png",
    templateName: "Video Streaming And Content Sharing Template",
    rating: 9,
    reviews: 203,
    price: 65,
    coin: 12,
    tier: "free",
    category: "portfolio",
    under: "templates",
  },
  {
    id: 489,
    owner: "Oliver K. Thompson",
    image: "/images/Marketing/user--8.avif",
    template: "/images/Marketing/template--1.png",
    templateName: "Online Course Enrollment And Tracking Template",
    rating: 7,
    reviews: 98,
    price: 55,
    coin: 8,
    tier: "free",
    category: "portfolio",
    under: "templates",
  },
  {
    id: 912,
    owner: "Ava M. Wilson",
    image: "/images/Marketing/user--8.avif",
    template: "/images/Marketing/template--2.png",
    templateName: "Document Collaboration And Editing Portal Template",
    rating: 9,
    reviews: 276,
    price: 95,
    coin: 18,
    tier: "paid",
    category: "portfolio",
    under: "templates",
  },
  {
    id: 347,
    owner: "Liam J. Anderson",
    image: "/images/Marketing/user--9.avif",
    template: "/images/Marketing/portfolio--3.png",
    templateName: "Custom Data Analytics And Reports Template",
    rating: 8,
    reviews: 187,
    price: 75,
    coin: 14,
    tier: "free",
    category: "portfolio",
    under: "templates",
  },
  {
    id: 634,
    owner: "Emma R. Taylor",
    image: "/images/postImages/user--1.avif",
    template: "/images/Marketing/template--4.png",
    templateName: "Cryptocurrency Trading Dashboard Template",
    rating: 9,
    reviews: 321,
    price: 110,
    coin: 22,
    tier: "paid",
    category: "business-corporate",
    under: "templates",
  },
  {
    id: 278,
    owner: "Noah S. Brown",
    image: "/images/postImages/user--4.avif",
    template: "/images/Marketing/template--6.png",
    templateName: "Fitness Tracker And Workout Planner Template",
    rating: 7,
    reviews: 156,
    price: 60,
    coin: 11,
    tier: "free",
    category: "business-corporate",
    under: "templates",
  },
  {
    id: 795,
    owner: "Isabella D. Martinez",
    image: "/images/postImages/user--1.avif",
    template: "/images/Marketing/template--2.png",
    templateName: "Interactive Quiz And Survey Creator Template",
    rating: 8,
    reviews: 234,
    price: 85,
    coin: 17,
    tier: "paid",
    category: "business-corporate",
    under: "templates",
  },
  {
    id: 513,
    owner: "Mason P. Lee",
    image: "/images/postImages/user--1.avif",
    template: "/images/Marketing/template--8.png",
    templateName: "Fitness Tracker And Workout Planner Template",
    rating: 9,
    reviews: 289,
    price: 95,
    coin: 19,
    tier: "paid",
    category: "business-corporate",
    under: "templates",
  },
  {
    id: 861,
    owner: "Charlotte G. Davis",
    image: "/images/postImages/user--1.avif",
    template: "/images/Marketing/template--7.png",
    templateName: "Interactive Quiz And Survey Creator Template",
    rating: 7,
    reviews: 178,
    price: 70,
    coin: 13,
    tier: "free",
    category: "business-corporate",
    under: "templates",
  },
  {
    id: 427,
    owner: "William H. Johnson",
    image: "/images/Marketing/user--10.avif",
    template: "/images/Marketing/template--4.png",
    templateName: "Online Event Ticket Booking Portal Template",
    rating: 8,
    reviews: 245,
    price: 80,
    coin: 16,
    tier: "paid",
    category: "e-commerce",
    under: "templates",
  },
  {
    id: 639,
    owner: "Amelia K. Smith",
    image: "/images/Marketing/user--11.avif",
    template: "/images/Marketing/template--1.png",
    templateName: "Restaurant Order Management System Template",
    rating: 9,
    reviews: 312,
    price: 105,
    coin: 21,
    tier: "paid",
    category: "e-commerce",
    under: "templates",
  },
  {
    id: 184,
    owner: "James F. Williams",
    image: "/images/Marketing/user--11.avif",
    template: "/images/Marketing/template--2.png",
    templateName: "Learning Management System Dashboard Template",
    rating: 7,
    reviews: 167,
    price: 65,
    coin: 12,
    tier: "free",
    category: "e-commerce",
    under: "templates",
  },
  {
    id: 952,
    owner: "Evelyn N. Brown",
    image: "/images/Marketing/user--11.avif",
    template: "/images/Marketing/template--7.png",
    templateName: "Healthcare Appointment Scheduling System Template",
    rating: 8,
    reviews: 223,
    price: 90,
    coin: 18,
    tier: "paid",
    category: "e-commerce",
    under: "templates",
  },
  {
    id: 376,
    owner: "Benjamin L. Jones",
    image: "/images/postImages/user--1.avif",
    template: "/images/Marketing/template--4.jpg",
    templateName: "Multi Vendor Ecommerce Marketplace Template",
    rating: 9,
    reviews: 298,
    price: 100,
    coin: 20,
    tier: "paid",
    category: "education",
    under: "templates",
  },
  {
    id: 741,
    owner: "Mia C. Miller",
    image: "/images/Marketing/user--9.avif",
    template: "/images/Marketing/template--11.png",
    templateName: "Job Posting And Recruitment Portal Template",
    rating: 7,
    reviews: 189,
    price: 75,
    coin: 15,
    tier: "free",
    category: "education",
    under: "templates",
  },
  {
    id: 528,
    owner: "Elijah A. Davis",
    image: "/images/Marketing/user--9.avif",
    template: "/images/Marketing/template--5.jpg",
    templateName: "Cloud Storage And File Sharing Template",
    rating: 8,
    reviews: 256,
    price: 85,
    coin: 17,
    tier: "paid",
    category: "education",
    under: "templates",
  },
  {
    id: 693,
    owner: "Harper E. Garcia",
    image: "/images/Marketing/user--9.avif",
    template: "/images/Marketing/template--2.png",
    templateName: "Project Management And Collaboration Template",
    rating: 9,
    reviews: 334,
    price: 110,
    coin: 22,
    tier: "paid",
    category: "education",
    under: "templates",
  },
  {
    id: 215,
    owner: "Alexander T. Rodriguez",
    image: "/images/Marketing/user--10.avif",
    template: "/images/Marketing/template--7.png",
    templateName: "Real Estate Property Listing Platform Template",
    rating: 7,
    reviews: 178,
    price: 70,
    coin: 14,
    tier: "free",
    category: "health-fitness",
    under: "templates",
  },
  {
    id: 879,
    owner: "Abigail R. Wilson",
    image: "/images/Marketing/user--9.avif",
    template: "/images/Marketing/template--6.png",
    templateName: "Interactive Heat map Visualization Dashboard Template",
    rating: 8,
    reviews: 267,
    price: 95,
    coin: 19,
    tier: "paid",
    category: "health-fitness",
    under: "templates",
  },
  {
    id: 462,
    owner: "Daniel M. Martinez",
    image: "/images/Marketing/user--8.avif",
    template: "/images/Marketing/template--2.png",
    templateName: "Customizable Email Newsletter Builder Template",
    rating: 9,
    reviews: 312,
    price: 105,
    coin: 21,
    tier: "paid",
    category: "health-fitness",
    under: "templates",
  },
  {
    id: 137,
    owner: "Sofia J. Anderson",
    image: "/images/Marketing/user--8.avif",
    template: "/images/Marketing/template--1.png",
    templateName: "LuxeLine - ",
    rating: 7,
    reviews: 201,
    price: 80,
    coin: 16,
    tier: "free",
    category: "health-fitness",
    under: "templates",
  },
  {
    id: 584,
    owner: "Michael K. Taylor",
    image: "/images/Marketing/user--8.avif",
    template: "/images/Marketing/template--10.png",
    templateName: "LuxeLine - ",
    rating: 8,
    reviews: 245,
    price: 90,
    coin: 18,
    tier: "paid",
    category: "health-fitness",
    under: "templates",
  },
  {
    id: 926,
    owner: "Emily G. Thomas",
    image: "/images/postImages/user--1.avif",
    template: "/images/Marketing/template--11.png",
    templateName: "ModaMuse - ",
    rating: 9,
    reviews: 287,
    price: 100,
    coin: 20,
    tier: "paid",
    category: "personal-development",
    under: "templates",
  },
  {
    id: 359,
    owner: "Jacob H. Harris",
    image: "/images/postImages/user--1.avif",
    template: "/images/Marketing/template--7.png",
    templateName: "ModaMuse - ",
    rating: 7,
    reviews: 198,
    price: 75,
    coin: 15,
    tier: "free",
    category: "personal-development",
    under: "templates",
  },
  {
    id: 703,
    owner: "Madison L. Clark",
    image: "/images/postImages/user--1.avif",
    template: "/images/Marketing/template--8.png",
    templateName: "ModaMuse - ",
    rating: 8,
    reviews: 256,
    price: 85,
    coin: 17,
    tier: "paid",
    category: "personal-development",
    under: "templates",
  },
  {
    id: 481,
    owner: "Ethan B. Lewis",
    image: "/images/postImages/user--1.avif",
    template: "/images/Marketing/template--2.png",
    templateName: "ModaMuse - ",
    rating: 9,
    reviews: 321,
    price: 110,
    coin: 22,
    tier: "paid",
    category: "personal-development",
    under: "templates",
  },
  {
    id: 847,
    owner: "Olivia S. Lee",
    image: "/images/postImages/user--1.avif",
    template: "/images/Marketing/template--10.png",
    templateName: "ModaMuse - ",
    rating: 7,
    reviews: 187,
    price: 70,
    coin: 14,
    tier: "free",
    category: "personal-development",
    under: "templates",
  },
  {
    id: 592,
    owner: "David R. Walker",
    image: "/images/postImages/user--2.avif",
    template: "/images/Marketing/template--8.png",
    templateName: "RunwayRhapsody - ",
    rating: 8,
    reviews: 278,
    price: 95,
    coin: 19,
    tier: "paid",
    category: "infographics",
    under: "templates",
  },

  {
    id: 8822,
    owner: "David R. Walker",
    image: "/images/postImages/user--2.avif",
    template: "/images/Marketing/template--8.png",
    templateName: "RunwayRhapsody - ",
    rating: 8,
    reviews: 278,
    price: 95,
    coin: 19,
    tier: "paid",
    category: "finance",
    under: "templates",
  },
];

////////////////////////
////////////////////////
////////////////////////
////////////////////////
////////////////////////
////////////////////////
////////////////////////
////////////////////////
////////////////////////
////////////////////////
////////////////////////
////////////////////////
////////////////////////
////////////////////////
////////////////////////
////////////////////////
////////////////////////
////////////////////////
////////////////////////
////////////////////////
////////////////////////
////////////////////////
////////////////////////
////////////////////////
////////////////////////
////////////////////////
////////////////////////
////////////////////////
////////////////////////
////////////////////////

const presentations = [
  {
    id: 9,
    owner: "Mary B. Bogar",
    image: "/images/postImages/user--1.avif",
    template: "/images/Marketing/template--4.jpg",
    templateName: "UrbanUtopia - ",
    rating: 6,
    reviews: 39,
    price: 70,
    coin: 10,
    tier: "free",
    category: "education",
    under: "persentations",
  },

  {
    id: 95,
    owner: "Mary B. Bogar",
    image: "/images/Marketing/user--9.avif",
    template: "/images/Marketing/template--11.png",
    templateName: "UrbanUtopia - ",
    rating: 6,
    reviews: 39,
    price: 70,
    coin: 10,
    tier: "paid",
    category: "education",
    under: "persentations",
  },

  {
    id: 91,
    owner: "Mary B. Bogar",
    image: "/images/Marketing/user--9.avif",
    template: "/images/Marketing/template--5.jpg",
    templateName: "UrbanUtopia - ",
    rating: 6,
    reviews: 39,
    price: 70,
    coin: 10,
    tier: "paid",
    category: "education",
    under: "persentations",
  },

  {
    id: 90,
    owner: "Mary B. Bogar",
    image: "/images/Marketing/user--9.avif",
    template: "/images/Marketing/template--2.png",
    templateName: "UrbanUtopia - ",
    rating: 6,
    reviews: 39,
    price: 70,
    coin: 10,
    tier: "paid",
    category: "portfolio",
    under: "persentations",
  },

  {
    id: 10,
    owner: "Mary B. Bogar",
    image: "/images/Marketing/user--9.avif",
    template: "/images/Marketing/template--9.jpg",
    templateName: "UrbanUtopia - ",
    rating: 6,
    reviews: 39,
    price: 70,
    coin: 10,
    tier: "paid",
    category: "portfolio",
    under: "persentations",
  },

  {
    id: 288,
    owner: "Mary B. Bogar",
    image: "/images/Marketing/user--9.avif",
    template: "/images/Marketing/template--9.jpg",
    templateName: "UrbanUtopia - ",
    rating: 6,
    reviews: 39,
    price: 70,
    coin: 10,
    tier: "paid",
    category: "portfolio",
    under: "persentations",
  },

  {
    id: 266,
    owner: "Mary B. Bogar",
    image: "/images/Marketing/user--9.avif",
    template: "/images/Marketing/template--9.jpg",
    templateName: "UrbanUtopia - ",
    rating: 6,
    reviews: 39,
    price: 70,
    coin: 10,
    tier: "paid",
    category: "portfolio",
    under: "persentations",
  },

  {
    id: 11,
    owner: "Imogene M. Anderson",
    image: "/images/Marketing/user--10.avif",
    template: "/images/Marketing/template--7.png",
    templateName: "SleekSpectrum - ",
    rating: 6,
    reviews: 145,
    price: 70,
    coin: 10,
    tier: "free",
    category: "health-fitness",
    under: "persentations",
  },

  {
    id: 12,
    owner: "Imogene M. Anderson",
    image: "/images/Marketing/user--9.avif",
    template: "/images/Marketing/template--6.png",
    templateName: "SleekSpectrum - ",
    rating: 6,
    reviews: 145,
    price: 70,
    coin: 10,
    tier: "free",
    category: "health-fitness",
    under: "persentations",
  },

  {
    id: 78,
    owner: "Imogene M. Anderson",
    image: "/images/Marketing/user--9.avif",
    template: "/images/Marketing/template--6.png",
    templateName: "SleekSpectrum - ",
    rating: 6,
    reviews: 145,
    price: 70,
    coin: 10,
    tier: "free",
    category: "health-fitness",
    under: "persentations",
  },

  {
    id: 56,
    owner: "Imogene M. Anderson",
    image: "/images/Marketing/user--9.avif",
    template: "/images/Marketing/template--6.png",
    templateName: "SleekSpectrum - ",
    rating: 6,
    reviews: 145,
    price: 70,
    coin: 10,
    tier: "free",
    category: "health-fitness",
    under: "persentations",
  },

  {
    id: 100,
    owner: "Imogene M. Anderson",
    image: "/images/Marketing/user--8.avif",
    template: "/images/Marketing/template--2.png",
    templateName: "SleekSpectrum - ",
    rating: 6,
    reviews: 145,
    price: 70,
    coin: 10,
    tier: "paid",
    category: "health-fitness",
    under: "persentations",
  },

  {
    id: 89,
    owner: "Imogene M. Anderson",
    image: "/images/Marketing/user--8.avif",
    template: "/images/Marketing/template--1.png",
    templateName: "SleekSpectrum - ",
    rating: 6,
    reviews: 145,
    price: 70,
    coin: 10,
    tier: "paid",
    category: "health-fitness",
    under: "persentations",
  },

  {
    id: 1789,
    owner: "Olivia Sophia",
    image: "/images/postImages/user--4.avif",
    template: "/images/Marketing/template--1.png",
    templateName: "RegalRevolution - UI Interface",
    rating: 3,
    reviews: 106,
    price: 173,
    coin: 20,
    tier: "paid",
    category: "portfolio",
    under: "persentations",
  },

  {
    id: 26789,
    owner: "Rodney R. Emerson",
    image: "/images/postImages/user--1.avif",
    template: "/images/Marketing/template--2.png",
    templateName: "EleganceEssence - UX Designer",
    rating: 6,
    reviews: 300,
    price: 30,
    coin: 10,
    tier: "free",
    category: "portfolio",
    under: "persentations",
  },

  {
    id: 801,
    owner: "Josephine M. Compton",
    image: "/images/postImages/user--1.avif",
    template: "/images/Marketing/template--7.png",
    templateName: "GlamGrid - ",
    rating: 6,
    reviews: 78,
    price: 70,
    coin: 10,
    tier: "free",
    category: "business-corporate",
    under: "persentations",
  },

  {
    id: 300000,
    owner: "Georgia M. Russo",
    image: "/images/postImages/user--3.avif",
    template: "/images/Marketing/template--3.png",
    templateName: "ModaMuse - ",
    rating: 6,
    reviews: 300,
    price: 70,
    coin: 10,
    tier: "paid",
    category: "portfolio",
    under: "persentations",
  },

  {
    id: 700000,
    owner: "Andrea R. Peachey",
    image: "/images/Marketing/user--10.avif",
    template: "/images/Marketing/template--4.png",
    templateName: "GlamGrid - ",
    rating: 6,
    reviews: 78,
    price: 70,
    coin: 10,
    tier: "paid",
    category: "e-commerce",
    under: "persentations",
  },

  {
    id: 106786,
    owner: "Andrea R. Peachey",
    image: "/images/Marketing/user--11.avif",
    template: "/images/Marketing/template--4.png",
    templateName: "GlamGrid - ",
    rating: 6,
    reviews: 78,
    price: 70,
    coin: 10,
    tier: "paid",
    category: "e-commerce",
    under: "persentations",
  },

  {
    id: 1023444,
    owner: "Andrea R. Peachey",
    image: "/images/Marketing/user--11.avif",
    template: "/images/Marketing/template--1.png",
    templateName: "GlamGrid - ",
    rating: 6,
    reviews: 78,
    price: 70,
    coin: 10,
    tier: "paid",
    category: "e-commerce",
    under: "persentations",
  },

  {
    id: 1012342,
    owner: "Andrea R. Peachey",
    image: "/images/Marketing/user--11.avif",
    template: "/images/Marketing/template--2.png",
    templateName: "GlamGrid - ",
    rating: 6,
    reviews: 78,
    price: 70,
    coin: 10,
    tier: "paid",
    category: "e-commerce",
    under: "persentations",
  },

  {
    id: 8342423,
    owner: "Andrea R. Peachey",
    image: "/images/Marketing/user--11.avif",
    template: "/images/Marketing/template--7.png",
    templateName: "GlamGrid - ",
    rating: 6,
    reviews: 78,
    price: 70,
    coin: 10,
    tier: "paid",
    category: "e-commerce",
    under: "persentations",
  },

  {
    id: 90324130,
    owner: "Mary B. Bogar",
    image: "/images/postImages/user--1.avif",
    template: "/images/Marketing/template--4.jpg",
    templateName: "UrbanUtopia - ",
    rating: 6,
    reviews: 39,
    price: 70,
    coin: 10,
    tier: "free",
    category: "education",
    under: "persentations",
  },

  {
    id: 9576816,
    owner: "Mary B. Bogar",
    image: "/images/Marketing/user--9.avif",
    template: "/images/Marketing/template--11.png",
    templateName: "UrbanUtopia - ",
    rating: 6,
    reviews: 39,
    price: 70,
    coin: 10,
    tier: "paid",
    category: "education",
    under: "persentations",
  },

  {
    id: 380299,
    owner: "Mary B. Bogar",
    image: "/images/Marketing/user--9.avif",
    template: "/images/Marketing/template--5.jpg",
    templateName: "UrbanUtopia - ",
    rating: 6,
    reviews: 39,
    price: 70,
    coin: 10,
    tier: "paid",
    category: "education",
    under: "persentations",
  },

  {
    id: 497382990,
    owner: "Mary B. Bogar",
    image: "/images/Marketing/user--9.avif",
    template: "/images/Marketing/template--2.png",
    templateName: "UrbanUtopia - ",
    rating: 6,
    reviews: 39,
    price: 70,
    coin: 10,
    tier: "paid",
    category: "education",
    under: "persentations",
  },

  {
    id: 200732930,
    owner: "Mary B. Bogar",
    image: "/images/Marketing/user--9.avif",
    template: "/images/Marketing/template--9.jpg",
    templateName: "UrbanUtopia - ",
    rating: 6,
    reviews: 39,
    price: 70,
    coin: 10,
    tier: "paid",
    category: "education",
    under: "persentations",
  },

  {
    id: 172392310,
    owner: "Imogene M. Anderson",
    image: "/images/Marketing/user--10.avif",
    template: "/images/Marketing/template--7.png",
    templateName: "SleekSpectrum - ",
    rating: 6,
    reviews: 145,
    price: 70,
    coin: 10,
    tier: "free",
    category: "health-fitness",
    under: "persentations",
  },

  {
    id: 1238732102,
    owner: "Imogene M. Anderson",
    image: "/images/Marketing/user--9.avif",
    template: "/images/Marketing/template--6.png",
    templateName: "SleekSpectrum - ",
    rating: 6,
    reviews: 145,
    price: 70,
    coin: 10,
    tier: "free",
    category: "health-fitness",
    under: "persentations",
  },

  {
    id: 88633,
    owner: "Imogene M. Anderson",
    image: "/images/Marketing/user--8.avif",
    template: "/images/Marketing/template--2.png",
    templateName: "SleekSpectrum - ",
    rating: 6,
    reviews: 145,
    price: 70,
    coin: 10,
    tier: "paid",
    category: "health-fitness",
    under: "persentations",
  },

  {
    id: 89027,
    owner: "Imogene M. Anderson",
    image: "/images/Marketing/user--8.avif",
    template: "/images/Marketing/template--10.png",
    templateName: "SleekSpectrum - ",
    rating: 6,
    reviews: 145,
    price: 70,
    coin: 10,
    tier: "paid",
    category: "health-fitness",
    under: "persentations",
  },

  {
    id: 637892,
    owner: "Imogene M. Anderson",
    image: "/images/Marketing/user--8.avif",
    template: "/images/Marketing/template--2.png",
    templateName: "SleekSpectrum - ",
    rating: 6,
    reviews: 145,
    price: 70,
    coin: 10,
    tier: "paid",
    category: "health-fitness",
    under: "persentations",
  },

  {
    id: 29380,
    owner: "Imogene M. Anderson",
    image: "/images/Marketing/user--8.avif",
    template: "/images/Marketing/template--6.png",
    templateName: "SleekSpectrum - ",
    rating: 6,
    reviews: 145,
    price: 70,
    coin: 10,
    tier: "paid",
    category: "health-fitness",
    under: "persentations",
  },

  {
    id: 7129,
    owner: "Imogene M. Anderson",
    image: "/images/Marketing/user--8.avif",
    template: "/images/Marketing/template--10.png",
    templateName: "SleekSpectrum - ",
    rating: 6,
    reviews: 145,
    price: 70,
    coin: 10,
    tier: "paid",
    category: "health-fitness",
    under: "persentations",
  },

  {
    id: 13434,
    owner: "Imogene M. Anderson",
    image: "/images/Marketing/user--8.avif",
    template: "/images/Marketing/template--3.png",
    templateName: "SleekSpectrum - ",
    rating: 6,
    reviews: 145,
    price: 70,
    coin: 10,
    tier: "paid",
    category: "health-fitness",
    under: "persentations",
  },

  {
    id: 14964,
    owner: "Olivia Sophia",
    image: "/images/postImages/user--1.avif",
    template: "/images/Marketing/template--5.jpg",
    templateName: "RunwayRhapsody - ",
    rating: 6,
    reviews: 245,
    price: 30,
    coin: 10,
    tier: "free",
    category: "charity",
    under: "persentations",
  },

  {
    id: 15893264,
    owner: "Olivia Sophia",
    image: "/images/postImages/user--2.avif",
    template: "/images/Marketing/template--3.jpg",
    templateName: "RunwayRhapsody - ",
    rating: 6,
    reviews: 245,
    price: 30,
    coin: 10,
    tier: "paid",
    category: "charity",
    under: "persentations",
  },

  {
    id: 747083,
    owner: "Olivia Sophia",
    image: "/images/postImages/user--2.avif",
    template: "/images/Marketing/template--9.jpg",
    templateName: "RunwayRhapsody - ",
    rating: 6,
    reviews: 245,
    price: 30,
    coin: 10,
    tier: "paid",
    category: "charity",
    under: "persentations",
  },

  {
    id: 77823331,
    owner: "Olivia Sophia",
    image: "/images/postImages/user--2.avif",
    template: "/images/Marketing/template--1.png",
    templateName: "RunwayRhapsody - ",
    rating: 6,
    reviews: 245,
    price: 30,
    coin: 10,
    tier: "paid",
    category: "charity",
    under: "persentations",
  },

  {
    id: 77330,
    owner: "Olivia Sophia",
    image: "/images/postImages/user--2.avif",
    template: "/images/Marketing/template--2.png",
    templateName: "RunwayRhapsody - ",
    rating: 6,
    reviews: 245,
    price: 30,
    coin: 10,
    tier: "paid",
    category: "charity",
    under: "persentations",
  },

  {
    id: 1383936,
    owner: "Denise C. Woodcock",
    image: "/images/postImages/user--4.avif",
    template: "/images/Marketing/template--6.png",
    templateName: "HauteHarmony - ",
    rating: 6,
    reviews: 300,
    price: 70,
    coin: 10,
    tier: "free",
    category: "real-estate",
    under: "persentations",
  },

  {
    id: 17423,
    owner: "Denise C. Woodcock",
    image: "/images/postImages/user--3.avif",
    template: "/images/Marketing/template--8.png",
    templateName: "HauteHarmony - ",
    rating: 6,
    reviews: 300,
    price: 70,
    coin: 10,
    tier: "free",
    category: "real-estate",
    under: "persentations",
  },

  {
    id: 584567890,
    owner: "Denise C. Woodcock",
    image: "/images/postImages/user--3.avif",
    template: "/images/Marketing/template--10.png",
    templateName: "HauteHarmony - ",
    rating: 6,
    reviews: 300,
    price: 70,
    coin: 10,
    tier: "free",
    category: "real-estate",
    under: "persentations",
  },

  {
    id: 550987672,
    owner: "Denise C. Woodcock",
    image: "/images/postImages/user--3.avif",
    template: "/images/Marketing/template--7.png",
    templateName: "HauteHarmony - ",
    rating: 6,
    reviews: 300,
    price: 70,
    coin: 10,
    tier: "free",
    category: "real-estate",
    under: "persentations",
  },

  {
    id: 546378923,
    owner: "Denise C. Woodcock",
    image: "/images/postImages/user--3.avif",
    template: "/images/Marketing/template--9.png",
    templateName: "HauteHarmony - ",
    rating: 6,
    reviews: 300,
    price: 70,
    coin: 10,
    tier: "free",
    category: "real-estate",
    under: "persentations",
  },

  {
    id: 56281022,
    owner: "Denise C. Woodcock",
    image: "/images/postImages/user--3.avif",
    template: "/images/Marketing/template--2.png",
    templateName: "HauteHarmony - ",
    rating: 6,
    reviews: 300,
    price: 70,
    coin: 10,
    tier: "free",
    category: "real-estate",
    under: "persentations",
  },

  {
    id: 51294733781,
    owner: "Denise C. Woodcock",
    image: "/images/postImages/user--3.avif",
    template: "/images/Marketing/template--4.png",
    templateName: "HauteHarmony - ",
    rating: 6,
    reviews: 300,
    price: 70,
    coin: 10,
    tier: "free",
    category: "real-estate",
    under: "persentations",
  },

  {
    id: 5161829340,
    owner: "Denise C. Woodcock",
    image: "/images/postImages/user--3.avif",
    template: "/images/Marketing/template--9.png",
    templateName: "HauteHarmony - ",
    rating: 6,
    reviews: 300,
    price: 70,
    coin: 10,
    tier: "free",
    category: "real-estate",
    under: "persentations",
  },

  {
    id: 18578193097652,
    owner: "Rachel V. Planas",
    image: "/images/postImages/user--6.avif",
    template: "/images/Marketing/template--4.png",
    templateName: "LuxeLine - ",
    rating: 6,
    reviews: 189,
    price: 180,
    coin: 10,
    tier: "paid",
    category: "finance",
    under: "persentations",
  },

  {
    id: 457292474,
    owner: "Rachel V. Planas",
    image: "/images/postImages/user--3.avif",
    template: "/images/Marketing/template--9.jpg",
    templateName: "LuxeLine - ",
    rating: 6,
    reviews: 189,
    price: 180,
    coin: 10,
    tier: "free",
    category: "finance",
    under: "persentations",
  },

  {
    id: 4076238913,
    owner: "Rachel V. Planas",
    image: "/images/postImages/user--3.avif",
    template: "/images/Marketing/template--2.png",
    templateName: "LuxeLine - ",
    rating: 6,
    reviews: 189,
    price: 180,
    coin: 10,
    tier: "free",
    category: "finance",
    under: "persentations",
  },
  {
    id: 43768923998302,
    owner: "Rachel V. Planas",
    image: "/images/postImages/user--3.avif",
    template: "/images/Marketing/template--5.jpg",
    templateName: "LuxeLine - ",
    rating: 6,
    reviews: 189,
    price: 180,
    coin: 10,
    tier: "free",
    category: "finance",
    under: "persentations",
  },

  {
    id: 427682397028232,
    owner: "Rachel V. Planas",
    image: "/images/postImages/user--3.avif",
    template: "/images/Marketing/template--1.png",
    templateName: "LuxeLine - ",
    rating: 6,
    reviews: 189,
    price: 180,
    coin: 10,
    tier: "free",
    category: "finance",
    under: "persentations",
  },

  {
    id: 4172389208,
    owner: "Rachel V. Planas",
    image: "/images/postImages/user--3.avif",
    template: "/images/Marketing/template--2.png",
    templateName: "LuxeLine - ",
    rating: 6,
    reviews: 189,
    price: 180,
    coin: 10,
    tier: "free",
    category: "finance",
    under: "persentations",
  },

  {
    id: 19678923093,
    owner: "Rachel V. Planas",
    image: "/images/postImages/user--3.avif",
    template: "/images/Marketing/template--5.jpg",
    templateName: "LuxeLine - ",
    rating: 6,
    reviews: 189,
    price: 180,
    coin: 10,
    tier: "free",
    category: "finance",
    under: "persentations",
  },

  {
    id: 209287647830,
    owner: "Anna J. Frederick",
    image: "/images/postImages/user--1.avif",
    template: "/images/Marketing/template--11.png",
    templateName: "ModaMuse - ",
    rating: 6,
    reviews: 286,
    price: 70,
    coin: 10,
    tier: "free",
    category: "personal-development",
    under: "persentations",
  },
];
